### ISSUE TITLE
unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by wenjie-6** [mgao6767/frds#4]
**Describe the bug**
unsupported operand type(s) for |: 'type' and 'type'

**To reproduce**
This is an example provided by https://frds.io/measures/srisk/#frds.measures.srisk.estimate

from frds.measures.srisk import estimate as srisk
import yfinance as yf
import numpy as np
df = yf.download(tickers="SPY JPM GS", start="2017-01-01", end="2022-12-31",
        progress=False, rounding=True) 
df = df[['Adj Close']]
df.columns = df.columns.droplevel(0)
df

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Python version [Python3.9.13]

**Additional context**
![SRISK-error](https://github.com/mgao6767/frds/assets/143416410/d2b987d6-31a2-4e99-9f37-2d84e217c7ea)

**Comment by mgao6767** [comment]
Hi @wenjie-6, the error is because I used a Python 3.10 feature (`|`) for typing. This commit https://github.com/mgao6767/frds/commit/a82c051da73d8653360700821b1dc17f1e130fb1 should fix the issue. 
Alternatively, you can use Python 3.10 to run the example. I might bump the required Python version later... Not sure.

**Comment by wenjie-6** [comment]
Dear Adrian Gao：
        I have received your reply and thank you very much for your answers to my questions. After using the two methods you proposed, SRISK was able to function normally, but the results of both methods were different from the ones shown in your example. This may be due to errors in stock data. Please find attached a screenshot of my data and the running results (which were obtained by running under Python 3.10.9 and modified using the method of a82c051, but unfortunately they were not saved). Finally, thank you again for your help and hard work!
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Adrian ***@***.***>
            
        
      
      
        
         Date 
        
        
        8/29/2023 17:05
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [mgao6767/frds] unsupported operand type(s) for |: 'type' and 'type' (Issue #4)
        
      
    
  

Hi @wenjie-6, the error is because I used a Python 3.10 feature (|) for typing. This commit a82c051 should fix the issue.
Alternatively, you can use Python 3.10 to run the example. I might bump the required Python version later... Not sure.
